name: CI/CD Backend Innovatech

on:
  push:
    branches:
      - deploy

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Login en Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build y Push a Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/innovatech-backend:latest

      - name: Despliegue en AWS EC2 (Backend)
        uses: appleboy/ssh-action@master
        with:
          proxy_host: ${{ secrets.EC2_FRONT_HOST }}
          proxy_username: ${{ secrets.EC2_USER }}
          proxy_key: ${{ secrets.EC2_SSH_KEY }}
          host: ${{ secrets.EC2_BACK_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/innovatech-backend:latest
            docker stop innovatech-backend || true
            docker rm innovatech-backend || true
            docker run -d --name innovatech-backend -p 8080:8080 --network host ${{ secrets.DOCKER_USERNAME }}/innovatech-backend:latest